sonar.projectKey=AchachiSoftware_storm-site-mcp
sonar.organization=achachisoftware

sonar.projectName=storm-site-mcp
sonar.projectVersion=1.0

sonar.sources=.
sonar.inclusions=server.py
sonar.exclusions=**/__pycache__/**,**/*.pyc,har/**,config/**
sonar.python.version=3.12
